apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
images:
- name: 947944952216.dkr.ecr.ap-northeast-2.amazonaws.com/jaintest
  newName: 947944952216.dkr.ecr.ap-northeast-2.amazonaws.com/jaintest
  newTag: d4b67cdc
resources:
- ../base
patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- service-patch.yaml
